# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Haml::Parser; end
module ::Haml::Parser::ParseNode; end
